;;;; Bind H2 + TLS before asdf:test-system (no recursive OPERATE).

(let ((v (string-downcase (or (uiop:getenv "GRPC_PARITY_PEERS") ""))))
  (unless (member v '("" "0" "false" "no") :test #'string=)
    (format t "~&; ci: pre-test GRPC_PARITY_PEERS — http-backend-async + libuv~%")
    (asdf:load-system "http-backend-async")
    (asdf:load-system "event-backend-libuv")
    (asdf:load-system "cl-stack-ssl")
    (ignore-errors (asdf:load-system "http2"))
    (ignore-errors (asdf:load-system "http2/client"))
    (ignore-errors (asdf:load-system "http2/server/threaded"))
    (ignore-errors (asdf:load-system "http-server-backend-http2"))
    (let ((ensure (find-symbol "ENSURE-TLS" :http-backend-async))
          (ensure-h2 (find-symbol "ENSURE-HTTP2" :http-backend-async)))
      (when (and ensure (fboundp ensure))
        (funcall ensure))
      (when (and ensure-h2 (fboundp ensure-h2))
        (funcall ensure-h2)))))
